# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gdcli < Formula
  desc "GoDaddy-focused domain investor CLI for OpenClaw"
  homepage "https://github.com/sportwhiz/gdcli"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sportwhiz/gdcli/releases/download/v0.1.8/gdcli_Darwin_x86_64.tar.gz"
      sha256 "52840fa88d7acd4b728762ac1c3f098d8ce2b3ec722f5741853eea992432538c"

      def install
        bin.install "gdcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sportwhiz/gdcli/releases/download/v0.1.8/gdcli_Darwin_arm64.tar.gz"
      sha256 "480b128cff82295812fb40b218eb382d7d2d0d54934f6d86e9ad794c400fdfce"

      def install
        bin.install "gdcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sportwhiz/gdcli/releases/download/v0.1.8/gdcli_Linux_x86_64.tar.gz"
      sha256 "956d6c1bed4e6cc32ee3bae4f5a78036b959eb2877c3a6e659d9cf07f1ec0769"
      def install
        bin.install "gdcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sportwhiz/gdcli/releases/download/v0.1.8/gdcli_Linux_arm64.tar.gz"
      sha256 "797c152d46505ac029242309a048b06355c9c05251555865cebadcbe193cada7"
      def install
        bin.install "gdcli"
      end
    end
  end

  test do
    system "#{bin}/gdcli", "help", "--json"
  end
end
